# Generated by Django 5.0.1 on 2024-03-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.TextField(default='')),
                ('place_id', models.TextField(default='', primary_key=True, serialize=False)),
                ('address', models.TextField(default='')),
                ('loc_latitude', models.FloatField(default=0)),
                ('loc_longitude', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('maps_url', models.TextField(default='')),
                ('menu_1_item', models.TextField(default='')),
                ('menu_1_price', models.TextField(default='')),
                ('menu_2_item', models.TextField(default='')),
                ('menu_2_price', models.TextField(default='')),
                ('menu_3_item', models.TextField(default='')),
                ('menu_3_price', models.TextField(default='')),
                ('keyword_1', models.TextField(default='')),
                ('keyword_2', models.TextField(default='')),
                ('keyword_3', models.TextField(default='')),
                ('keyword_4', models.TextField(default='')),
                ('keyword_5', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('url', models.TextField(default='', primary_key=True, serialize=False)),
                ('review', models.TextField(default='')),
            ],
        ),
    ]
