# Generated by Django 5.0.1 on 2024-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
