# Generated by Django 5.0.1 on 2024-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_remove_restaurant_id_remove_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
