# Generated by Django 5.0.1 on 2024-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_alter_restaurant_place_id_alter_review_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='keyword_1',
            new_name='tag_1',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='keyword_2',
            new_name='tag_2',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='keyword_3',
            new_name='tag_3',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='keyword_4',
            new_name='tag_4',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='keyword_5',
            new_name='tag_5',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_id',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.TextField(default='', primary_key=True, serialize=False),
        ),
    ]
