# Generated by Django 5.0.1 on 2024-03-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_rename_keyword_1_restaurant_tag_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='tag_1',
            new_name='keyword_1',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='tag_2',
            new_name='keyword_2',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='tag_3',
            new_name='keyword_3',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='tag_4',
            new_name='keyword_4',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='tag_5',
            new_name='keyword_5',
        ),
    ]
